// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA239cHQZ2LtVKd4FvkI39FKdf-njykPZ8',
    appId: '1:469474103344:web:c487d8a42d38a8254d1df5',
    messagingSenderId: '469474103344',
    projectId: 'saude-financeira-familia-e5ba5',
    authDomain: 'saude-financeira-familia-e5ba5.firebaseapp.com',
    storageBucket: 'saude-financeira-familia-e5ba5.firebasestorage.app',
    measurementId: 'G-VBEKZXRNZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7hsKFaX9y8oiouEyKNE7N4YA3w7wu9U',
    appId: '1:469474103344:android:d3b8f54e419726154d1df5',
    messagingSenderId: '469474103344',
    projectId: 'saude-financeira-familia-e5ba5',
    storageBucket: 'saude-financeira-familia-e5ba5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYmgvwuKC5ZjzMNUTYHk-eMCKu2ggUrbE',
    appId: '1:469474103344:ios:65ee403adbdcd7714d1df5',
    messagingSenderId: '469474103344',
    projectId: 'saude-financeira-familia-e5ba5',
    storageBucket: 'saude-financeira-familia-e5ba5.firebasestorage.app',
    iosBundleId: 'com.example.saudeFinanceiraFamiliar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYmgvwuKC5ZjzMNUTYHk-eMCKu2ggUrbE',
    appId: '1:469474103344:ios:65ee403adbdcd7714d1df5',
    messagingSenderId: '469474103344',
    projectId: 'saude-financeira-familia-e5ba5',
    storageBucket: 'saude-financeira-familia-e5ba5.firebasestorage.app',
    iosBundleId: 'com.example.saudeFinanceiraFamiliar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA239cHQZ2LtVKd4FvkI39FKdf-njykPZ8',
    appId: '1:469474103344:web:a5b8f647f3979ed14d1df5',
    messagingSenderId: '469474103344',
    projectId: 'saude-financeira-familia-e5ba5',
    authDomain: 'saude-financeira-familia-e5ba5.firebaseapp.com',
    storageBucket: 'saude-financeira-familia-e5ba5.firebasestorage.app',
    measurementId: 'G-GYT8VE0XHT',
  );
}
